In [12]:
import pandas as pd
import pickle

In [13]:
# Import insurance data file reviewed by the customers
insurance_df = pd.read_csv('Insurance_Feedback.csv')
insurance_df

,Timestamp,What is the Motor Insurance are you using?,How long have you been using Insurance Plan?,Vehicle Type,Vehicle Make,Vehicle Model,Provide honest opinion regarding the motor insurance experience you are using?,Rate your Insurance
0,2021/06/05 2:45:54 PM GMT+5:30,Sri Lanka Insurance,Between 1 -5 Years,Lorry,Ashok-Leyland,Cargo 1618,Good full insurance for heavy vehicles,4
1,2021/06/05 2:53:27 PM GMT+5:30,Cooperative Insurance Company Ltd.,Between 5 - 10 Years,Three Wheel,Bajaj,4 Stroke,Currently im satisfied with the service,3
2,2021/06/05 3:13:19 PM GMT+5:30,Fairfirst Insurance Limited,Less than 1 Year,Car,Toyota,Corolla 121,Provide good service for the customer,4
3,2021/06/05 3:28:14 PM GMT+5:30,Ceylinco General Insurance Limited,Between 5 - 10 Years,Car,Toyota,Vitz,Excellent service,5
4,2021/06/05 3:52:49 PM GMT+5:30,AIA Insurance Lanka Ltd.,Less than 1 Year,Car,Toyota,Yaris,Good,4
...,...,...,...,...,...,...,...,...
197,2021/07/01 11:26:38 PM GMT+5:30,Cooperative Insurance Company Ltd.,Between 1 -5 Years,Cab,Nissan,Navara,It was a first party insurance and had Nissan....,3
198,2021/07/01 11:29:48 PM GMT+5:30,Janashakthi Insurance PLC,Less than 1 Year,NaN,Yamaha,R1,I do not have any claim experience so far from...,4
199,2021/07/01 11:31:17 PM GMT+5:30,Sri Lanka Insurance,Between 5 - 10 Years,Car,Toyota,Corolla 121,Taken my car insurance from Sri Lanka Insuranc...,4
200,2021/07/01 11:33:32 PM GMT+5:30,HNB Assurance PLC,Between 1 -5 Years,Lorry,Tata,LPK 1615,Not any particular reason for choosing the com...,4
201,2021/07/01 11:36:09 PM GMT+5:30,HNB Assurance PLC,Between 1 -5 Years,Car,Mitsubishi,Lancer CK2,I had a claim experience with the car insuranc...,4

In [3]:
# Import insurance data file reviewed by the customers
insurance_df = pd.read_csv('Insurance_Feedback.csv')
insurance_df

,Timestamp,What is the Motor Insurance are you using?,How long have you been using Insurance Plan?,Vehicle Type,Vehicle Make,Vehicle Model,Provide honest opinion regarding the motor insurance experience you are using?,Rate your Insurance
0,2021/06/05 2:45:54 PM GMT+5:30,Sri Lanka Insurance,Between 1 -5 Years,Lorry,Ashok-Leyland,Cargo 1618,Good full insurance for heavy vehicles,4
1,2021/06/05 2:53:27 PM GMT+5:30,Cooperative Insurance Company Ltd.,Between 5 - 10 Years,Three Wheel,Bajaj,4 Stroke,Currently im satisfied with the service,3
2,2021/06/05 3:13:19 PM GMT+5:30,Fairfirst Insurance Limited,Less than 1 Year,Car,Toyota,Corolla 121,Provide good service for the customer,4
3,2021/06/05 3:28:14 PM GMT+5:30,Ceylinco General Insurance Limited,Between 5 - 10 Years,Car,Toyota,Vitz,Excellent service,5
4,2021/06/05 3:52:49 PM GMT+5:30,AIA Insurance Lanka Ltd.,Less than 1 Year,Car,Toyota,Yaris,Good,4
...,...,...,...,...,...,...,...,...
197,2021/07/01 11:26:38 PM GMT+5:30,Cooperative Insurance Company Ltd.,Between 1 -5 Years,Cab,Nissan,Navara,It was a first party insurance and had Nissan....,3
198,2021/07/01 11:29:48 PM GMT+5:30,Janashakthi Insurance PLC,Less than 1 Year,NaN,Yamaha,R1,I do not have any claim experience so far from...,4
199,2021/07/01 11:31:17 PM GMT+5:30,Sri Lanka Insurance,Between 5 - 10 Years,Car,Toyota,Corolla 121,Taken my car insurance from Sri Lanka Insuranc...,4
200,2021/07/01 11:33:32 PM GMT+5:30,HNB Assurance PLC,Between 1 -5 Years,Lorry,Tata,LPK 1615,Not any particular reason for choosing the com...,4
201,2021/07/01 11:36:09 PM GMT+5:30,HNB Assurance PLC,Between 1 -5 Years,Car,Mitsubishi,Lancer CK2,I had a claim experience with the car insuranc...,4

In [4]:
# Remove the string time from Timestamp, using .str.slice(start,stop,step) method
insurance_df['Timestamp'] = insurance_df['Timestamp'].str.slice(start=None,stop=11,step=1)
insurance_df

,Timestamp,What is the Motor Insurance are you using?,How long have you been using Insurance Plan?,Vehicle Type,Vehicle Make,Vehicle Model,Provide honest opinion regarding the motor insurance experience you are using?,Rate your Insurance
0,2021/06/05,Sri Lanka Insurance,Between 1 -5 Years,Lorry,Ashok-Leyland,Cargo 1618,Good full insurance for heavy vehicles,4
1,2021/06/05,Cooperative Insurance Company Ltd.,Between 5 - 10 Years,Three Wheel,Bajaj,4 Stroke,Currently im satisfied with the service,3
2,2021/06/05,Fairfirst Insurance Limited,Less than 1 Year,Car,Toyota,Corolla 121,Provide good service for the customer,4
3,2021/06/05,Ceylinco General Insurance Limited,Between 5 - 10 Years,Car,Toyota,Vitz,Excellent service,5
4,2021/06/05,AIA Insurance Lanka Ltd.,Less than 1 Year,Car,Toyota,Yaris,Good,4
...,...,...,...,...,...,...,...,...
197,2021/07/01,Cooperative Insurance Company Ltd.,Between 1 -5 Years,Cab,Nissan,Navara,It was a first party insurance and had Nissan....,3
198,2021/07/01,Janashakthi Insurance PLC,Less than 1 Year,NaN,Yamaha,R1,I do not have any claim experience so far from...,4
199,2021/07/01,Sri Lanka Insurance,Between 5 - 10 Years,Car,Toyota,Corolla 121,Taken my car insurance from Sri Lanka Insuranc...,4
200,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Lorry,Tata,LPK 1615,Not any particular reason for choosing the com...,4
201,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Car,Mitsubishi,Lancer CK2,I had a claim experience with the car insuranc...,4

In [5]:
#Rename the Columns
insurance_df.rename(columns={"Timestamp": "Date","What is the Motor Insurance are you using?": "Motor_Insurance","Vehicle Type": "Vehicle_Type","Vehicle Make": "Vehicle_Make","Vehicle Model": "Vehicle_Model","How long have you been using Insurance Plan?": "Years_of_experience","Provide honest opinion regarding the motor insurance experience you are using?": "Insurance_experience","Rate your Insurance": "Rate"}, inplace=True)
insurance_df

,Date,Motor_Insurance,Years_of_experience,Vehicle_Type,Vehicle_Make,Vehicle_Model,Insurance_experience,Rate
0,2021/06/05,Sri Lanka Insurance,Between 1 -5 Years,Lorry,Ashok-Leyland,Cargo 1618,Good full insurance for heavy vehicles,4
1,2021/06/05,Cooperative Insurance Company Ltd.,Between 5 - 10 Years,Three Wheel,Bajaj,4 Stroke,Currently im satisfied with the service,3
2,2021/06/05,Fairfirst Insurance Limited,Less than 1 Year,Car,Toyota,Corolla 121,Provide good service for the customer,4
3,2021/06/05,Ceylinco General Insurance Limited,Between 5 - 10 Years,Car,Toyota,Vitz,Excellent service,5
4,2021/06/05,AIA Insurance Lanka Ltd.,Less than 1 Year,Car,Toyota,Yaris,Good,4
...,...,...,...,...,...,...,...,...
197,2021/07/01,Cooperative Insurance Company Ltd.,Between 1 -5 Years,Cab,Nissan,Navara,It was a first party insurance and had Nissan....,3
198,2021/07/01,Janashakthi Insurance PLC,Less than 1 Year,NaN,Yamaha,R1,I do not have any claim experience so far from...,4
199,2021/07/01,Sri Lanka Insurance,Between 5 - 10 Years,Car,Toyota,Corolla 121,Taken my car insurance from Sri Lanka Insuranc...,4
200,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Lorry,Tata,LPK 1615,Not any particular reason for choosing the com...,4
201,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Car,Mitsubishi,Lancer CK2,I had a claim experience with the car insuranc...,4

In [6]:
# Merge 2 two data in to one column
insurance_df['Vehicle'] =insurance_df['Vehicle_Make'].astype(str) + ' ' + insurance_df['Vehicle_Model']
insurance_df

,Date,Motor_Insurance,Years_of_experience,Vehicle_Type,Vehicle_Make,Vehicle_Model,Insurance_experience,Rate,Vehicle
0,2021/06/05,Sri Lanka Insurance,Between 1 -5 Years,Lorry,Ashok-Leyland,Cargo 1618,Good full insurance for heavy vehicles,4,Ashok-Leyland Cargo 1618
1,2021/06/05,Cooperative Insurance Company Ltd.,Between 5 - 10 Years,Three Wheel,Bajaj,4 Stroke,Currently im satisfied with the service,3,Bajaj 4 Stroke
2,2021/06/05,Fairfirst Insurance Limited,Less than 1 Year,Car,Toyota,Corolla 121,Provide good service for the customer,4,Toyota Corolla 121
3,2021/06/05,Ceylinco General Insurance Limited,Between 5 - 10 Years,Car,Toyota,Vitz,Excellent service,5,Toyota Vitz
4,2021/06/05,AIA Insurance Lanka Ltd.,Less than 1 Year,Car,Toyota,Yaris,Good,4,Toyota Yaris
...,...,...,...,...,...,...,...,...,...
197,2021/07/01,Cooperative Insurance Company Ltd.,Between 1 -5 Years,Cab,Nissan,Navara,It was a first party insurance and had Nissan....,3,Nissan Navara
198,2021/07/01,Janashakthi Insurance PLC,Less than 1 Year,NaN,Yamaha,R1,I do not have any claim experience so far from...,4,Yamaha R1
199,2021/07/01,Sri Lanka Insurance,Between 5 - 10 Years,Car,Toyota,Corolla 121,Taken my car insurance from Sri Lanka Insuranc...,4,Toyota Corolla 121
200,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Lorry,Tata,LPK 1615,Not any particular reason for choosing the com...,4,Tata LPK 1615
201,2021/07/01,HNB Assurance PLC,Between 1 -5 Years,Car,Mitsubishi,Lancer CK2,I had a claim experience with the car insuranc...,4,Mitsubishi Lancer CK2

In [7]:
# Covert the Motor Insurance  column into uppercase
insurance_df['Motor_Insurance'] = insurance_df['Motor_Insurance'].str.upper()

# Covert the Vehicle Type column into uppercase
insurance_df['Vehicle_Type'] = insurance_df['Vehicle_Type'].str.upper()

# Covert the Vehicle Make column into uppercase
insurance_df['Vehicle_Make'] = insurance_df['Vehicle_Make'].str.upper()

# Covert the Vehicle Model column into uppercase
insurance_df['Vehicle_Model'] = insurance_df['Vehicle_Model'].str.upper()

# Covert the Insurance experience column into uppercase
insurance_df['Insurance_experience'] = insurance_df['Insurance_experience'].str.upper()

# Covert the Vehicle column into uppercase
insurance_df['Vehicle'] = insurance_df['Vehicle'].str.upper()
insurance_df

,Date,Motor_Insurance,Years_of_experience,Vehicle_Type,Vehicle_Make,Vehicle_Model,Insurance_experience,Rate,Vehicle
0,2021/06/05,SRI LANKA INSURANCE,Between 1 -5 Years,LORRY,ASHOK-LEYLAND,CARGO 1618,GOOD FULL INSURANCE FOR HEAVY VEHICLES,4,ASHOK-LEYLAND CARGO 1618
1,2021/06/05,COOPERATIVE INSURANCE COMPANY LTD.,Between 5 - 10 Years,THREE WHEEL,BAJAJ,4 STROKE,CURRENTLY IM SATISFIED WITH THE SERVICE,3,BAJAJ 4 STROKE
2,2021/06/05,FAIRFIRST INSURANCE LIMITED,Less than 1 Year,CAR,TOYOTA,COROLLA 121,PROVIDE GOOD SERVICE FOR THE CUSTOMER,4,TOYOTA COROLLA 121
3,2021/06/05,CEYLINCO GENERAL INSURANCE LIMITED,Between 5 - 10 Years,CAR,TOYOTA,VITZ,EXCELLENT SERVICE,5,TOYOTA VITZ
4,2021/06/05,AIA INSURANCE LANKA LTD.,Less than 1 Year,CAR,TOYOTA,YARIS,GOOD,4,TOYOTA YARIS
...,...,...,...,...,...,...,...,...,...
197,2021/07/01,COOPERATIVE INSURANCE COMPANY LTD.,Between 1 -5 Years,CAB,NISSAN,NAVARA,IT WAS A FIRST PARTY INSURANCE AND HAD NISSAN....,3,NISSAN NAVARA
198,2021/07/01,JANASHAKTHI INSURANCE PLC,Less than 1 Year,NaN,YAMAHA,R1,I DO NOT HAVE ANY CLAIM EXPERIENCE SO FAR FROM...,4,YAMAHA R1
199,2021/07/01,SRI LANKA INSURANCE,Between 5 - 10 Years,CAR,TOYOTA,COROLLA 121,TAKEN MY CAR INSURANCE FROM SRI LANKA INSURANC...,4,TOYOTA COROLLA 121
200,2021/07/01,HNB ASSURANCE PLC,Between 1 -5 Years,LORRY,TATA,LPK 1615,NOT ANY PARTICULAR REASON FOR CHOOSING THE COM...,4,TATA LPK 1615
201,2021/07/01,HNB ASSURANCE PLC,Between 1 -5 Years,CAR,MITSUBISHI,LANCER CK2,I HAD A CLAIM EXPERIENCE WITH THE CAR INSURANC...,4,MITSUBISHI LANCER CK2

In [8]:
# Write the Edited insurance reviews file to .csv
insurance_df.to_csv('insurance_review_cleaned.csv',index=False)

In [9]:
insurance_df

,Date,Motor_Insurance,Years_of_experience,Vehicle_Type,Vehicle_Make,Vehicle_Model,Insurance_experience,Rate,Vehicle
0,2021/06/05,SRI LANKA INSURANCE,Between 1 -5 Years,LORRY,ASHOK-LEYLAND,CARGO 1618,GOOD FULL INSURANCE FOR HEAVY VEHICLES,4,ASHOK-LEYLAND CARGO 1618
1,2021/06/05,COOPERATIVE INSURANCE COMPANY LTD.,Between 5 - 10 Years,THREE WHEEL,BAJAJ,4 STROKE,CURRENTLY IM SATISFIED WITH THE SERVICE,3,BAJAJ 4 STROKE
2,2021/06/05,FAIRFIRST INSURANCE LIMITED,Less than 1 Year,CAR,TOYOTA,COROLLA 121,PROVIDE GOOD SERVICE FOR THE CUSTOMER,4,TOYOTA COROLLA 121
3,2021/06/05,CEYLINCO GENERAL INSURANCE LIMITED,Between 5 - 10 Years,CAR,TOYOTA,VITZ,EXCELLENT SERVICE,5,TOYOTA VITZ
4,2021/06/05,AIA INSURANCE LANKA LTD.,Less than 1 Year,CAR,TOYOTA,YARIS,GOOD,4,TOYOTA YARIS
...,...,...,...,...,...,...,...,...,...
197,2021/07/01,COOPERATIVE INSURANCE COMPANY LTD.,Between 1 -5 Years,CAB,NISSAN,NAVARA,IT WAS A FIRST PARTY INSURANCE AND HAD NISSAN....,3,NISSAN NAVARA
198,2021/07/01,JANASHAKTHI INSURANCE PLC,Less than 1 Year,NaN,YAMAHA,R1,I DO NOT HAVE ANY CLAIM EXPERIENCE SO FAR FROM...,4,YAMAHA R1
199,2021/07/01,SRI LANKA INSURANCE,Between 5 - 10 Years,CAR,TOYOTA,COROLLA 121,TAKEN MY CAR INSURANCE FROM SRI LANKA INSURANC...,4,TOYOTA COROLLA 121
200,2021/07/01,HNB ASSURANCE PLC,Between 1 -5 Years,LORRY,TATA,LPK 1615,NOT ANY PARTICULAR REASON FOR CHOOSING THE COM...,4,TATA LPK 1615
201,2021/07/01,HNB ASSURANCE PLC,Between 1 -5 Years,CAR,MITSUBISHI,LANCER CK2,I HAD A CLAIM EXPERIENCE WITH THE CAR INSURANC...,4,MITSUBISHI LANCER CK2